################################################################################
# ADMIN STACK => docker stack deploy -c stacks/security/traefik/stack.yaml traefik
################################################################################

version: '3.8'

services:
  traefik:
    image: traefik:ramequin
    deploy:
      replicas: 1
      labels:
        homepage.group: Security
        homepage.name: Traefik
        homepage.icon: traefik.png
        homepage.href: https://traefik.lsarlinmagnus.fr
        homepage.widget.type: traefik
        homepage.widget.url: http://traefik:8080
        homepage.widget.fields: '["routers", "services", "middleware"]'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - 80:80
      # - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs_data:/var/traefik/certs/:rw
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yaml
      - source: traefik_middlewares
        target: /etc//traefik/files/middlewares.yaml
      - source: traefik_routers
        target: /etc//traefik/files/routers.yaml
      - source: traefik_services
        target: /etc//traefik/files/services.yaml
    secrets:
      - ovh_endpoint
      - ovh_application_key
      - ovh_application_secret
      - ovh_consumer_key
    environment:
      TZ: Europe/Paris
      OVH_ENDPOINT_FILE: /run/secrets/ovh_endpoint
      OVH_APPLICATION_KEY_FILE: /run/secrets/ovh_application_key
      OVH_APPLICATION_SECRET_FILE: /run/secrets/ovh_application_secret
      OVH_CONSUMER_KEY_FILE: /run/secrets/ovh_consumer_key
    networks:
      - proxy

  whoami:
    image: traefik/whoami:v1.11.0
    deploy:
      labels:
        sablier.enable: "true"
        sablier.group: whoami
        traefik.enable: "true"
        traefik.swarm.lbswarm: "true"
        traefik.http.routers.whoami.middlewares: whoami@swarm
        traefik.http.services.whoami.loadbalancer.server.port: 80
        traefik.http.routers.whoami.rule: Host(`new.lsarlinmagnus.fr`)
        traefik.http.routers.whoami.entrypoints: websecure
        traefik.http.routers.whoami.tls: "true"
        traefik.http.routers.whoami.tls.certresolver: ovh
        homepage.group: Security
        homepage.name: Whoami
        homepage.icon: traefik.png
        homepage.href: https://new.lsarlinmagnus.fr
    networks:
      - proxy

configs:
  traefik_config:
    file: ./traefik.yaml
  traefik_middlewares:
    file: ./files/middlewares.yaml
  traefik_routers:
    file: ./files/routers.yaml
  traefik_services:
    file: ./files/services.yaml

secrets:
  ovh_endpoint:
    file: ./secrets/ovh_endpoint.secret
  ovh_application_key:
    file: ./secrets/ovh_application_key.secret
  ovh_application_secret:
    file: ./secrets/ovh_application_secret.secret
  ovh_consumer_key:
    file: ./secrets/ovh_consumer_key.secret

networks:
  proxy:
    driver: overlay
    attachable: true
    name: proxy

volumes:
  traefik_certs_data:

  # crowdsec:
  #   image: crowdsecurity/crowdsec
  #   deploy:
  #     replicas: 1
  #   volumes:
  #     - ./crowdsec_data:/var/lib/crowdsec/data
  #   networks:
  #     - overlay_net