---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: homelab

language: fr

theme: dark
color: gray

target: _blank
background: 
  image: images/wallpaper.jpg
  # blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 150 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 80 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 75 # 0-100

cardBlur: xl

layout:
  Administration: 
    Security:
    Core:
  Services:
    Documents:
    Miscellaneous:
    Networking:
  Monitoring:
    Grafana:
  Pictures:
  Media:

disableCollapse: true
hideVersion: true
hideErrors: true
# showStats: true
useEqualHeights: true
# language: fr
